package constants

const (
	ENUM_ROLE_ADMIN = "admin"
	ENUM_ROLE_USER  = "user"

	ENUM_RUN_PRODUCTION = "production"
	ENUM_RUN_TESTING    = "testing"

	ENUM_PAGINATION_PER_PAGE = 10
	ENUM_PAGINATION_PAGE     = 1

	ENUM_MERCH_CATEGORY_TSHIRT	= "t-shirt"
	ENUM_MERCH_CATEGORY_CAP		= "cap"
	ENUM_MERCH_CATEGORY_STICKER = "sticker"
	ENUM_MERCH_CATEGORY_OTHER 	= "other"

	ENUM_ORDER_STATUS_PENDING 	= "pending"
	ENUM_ORDER_STATUS_PAID 		= "paid"
	ENUM_ORDER_STATUS_FAILED 	= "failed"
	ENUM_ORDER_STATUS_CANCELLED 	= "cancelled"
	ENUM_ORDER_STATUS_EXPIRED	= "expired"
	ENUM_ORDER_STATUS_REFUNDED 	= "refunded"

	ENUM_AUDIENCE_TYPE_UNAIR 	= "unair"
	ENUM_AUDIENCE_TYPE_UMUM 	= "umum"

	DB         = "db"
	JWTService = "JWTService"
)